import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Provider from "@/components/common/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />
      <body className={inter.className}>
        <div className=" text-center pt-6 pb-2 text-2xl font-bold text-orange-600">
          <h1>Cloco Nepal</h1>
        </div>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
